nodes:
  - id: input
    path: ../nodes/input_node/main.py
    outputs:
      - command

  - id: agent
    path: ../nodes/agent_node/main.py
    inputs:
      command: input/command
    outputs:
      - velocity

  - id: safety
    path: ../nodes/safety_node/main.py
    inputs:
      velocity: agent/velocity
    outputs:
      - safe_velocity

  - id: simulation
    path: ../nodes/simulation_node/simulation/robot.py
    inputs:
      safe_velocity: safety/safe_velocity
